language: python
cache: pip
notifications:
  email: "${HEROKU_EMAIL}"
python:
  - '3.6'
services:
  - docker
before_script:
  - pip install docker-compose
script:
  - docker-compose run --rm app sh -c "python manage.py makemigrations"
  - docker-compose run --rm  app sh -c "python manage.py migrate"
  - docker-compose run --rm  app sh -c "python manage.py showmigrations"
  - docker-compose run --rm  app sh -c "python manage.py test  && flake8  --ignore E501,F811"
deploy:
  provider: heroku
  app: restapis-django-basics
  api_key:
    secure: lOmMy452Fw7gl7vdCVn+yG0VDVC/NG3d7CQHSi+xM3I2S72DCdDYLHKv8bTB0ut3QVl/ZV2e2AakvcfHwfVrhfuwWFKBY1EtYiejC5vl1Dw9AIEhLdxYyCD8ZjeiuSb41vsBZSANnggjG///beGnv8fKKEoLb6IeTPd36h0YlqlXC9dQhGAfeALO1Hv54Om1DHN/9JqQPoVSUyoIAP/VDh+Wa5FMvgR8sTxp7V3cM4McSi7hWZvP7hg4vA7Fq0GcIvT3vba1kpDpFqzgpxGHkYDYi5YELPXGnQbZs8kPvdGRVWfdt9xGR1VAhVDC3bJeZoBDRGtZMb1/Kh9Y7YxiZahdP9YzbofZFHyHgXxNg+BJ4kQaPRPwYX6hcHdSnuzklGDfOH46BNdNWpanSSqaEBE67jB36oC7zP7tvHSdGrAC0WiYj/X3C5SjPrAiMk8jS7ADIOIKO6lgoS4L/L6DqbwATYsfSfeoLq9r8PYc/iwdrmKI/csE2wYjjq8GpVNNzxweyA2W60+1T46ARF364z0G0jBKLOjSZLhiJMVvuGIlLz2dpZbI24A5U+jSzgWGOVV6JH2/A9Y4kxjHYg8GM4KccYtFirm1cYUpjkX4aKjhEQ7YrHoKk5uDshBG5ycgGT+zUtYzCEflIpgDGWd2iB3TNGWZBWI4RvLwUlRcvlI=

  on:
    repo: everythingisdata/restapis-django-basics
    all_branches: true
