language: python
cache: pip #Cache pip dir
notifications:
  email: "${HEROKU_EMAIL}"

python:
  - "3.6"
services:
  - docker

before_script:
  - pip install docker-compose
# Run scripts
script:
  - docker-compose run --rm app sh -c "python manage.py makemigrations"
  - docker-compose run --rm  app sh -c "python manage.py migrate"
  - docker-compose run --rm  app sh -c "python manage.py showmigrations"
  - docker-compose run --rm  app sh -c "python manage.py test  && flake8  --ignore E501,F811"


deploy:
  provider: heroku
  cleanup: true
  edge: true
  api_key:
    secure: ${HEROKU_API_KEY}
  app: restapis-django-basics
  on:
    repo: everythingisdata/restapis-django-basics
    all_branches: true