language: python
cache: pip
notifications:
  email: "${HEROKU_EMAIL}"
python:
- '3.6'
services:
- docker
before_script:
- pip install docker-compose
script:
- docker-compose run --rm app sh -c "python manage.py makemigrations"
- docker-compose run --rm  app sh -c "python manage.py migrate"
- docker-compose run --rm  app sh -c "python manage.py test  && flake8  --ignore E501,F811"
deploy:
  provider: heroku
  app: restapis-django-basics
  api_key:
    secure: hja53ZjIVBAzS0JaMR57moEmtiqRuNtjW0TvlevuHCwxsP2yXuzGeB3YaFT8i1mo2HPu7yU3QftwwSsnM8K5dPcmukSJq4QeFguLLFgDHVb5PfGsHn0K9jYN9b0O09kUAfBUF9Cmp/gufJOf1bmIJq9p50Fk/VOt6v/rkkyeRKVbX5cM3xkywaSfMx8cwQb8V9D0MzHMvyFCDZz3tRcSXxakKdP134lC/dBv+EqQwyJ+OGKHreehBzIFasZRGk+OIRSl9Lofsf5L+rdzERtQgsdl3Bc7F1i322ihiw4Qiq9g7lXYwRXwEM2Q4Yd/fkwrzozeLFoykxH2MWUafvOIYO6h5kKmNbZm4oneuYCfJazJLC0y5yzoYEoEcrXKUgXE99PY5qLUs35i/PgqWxHjvFeUkfgpIUe6V81lPJ4yZxJvSwN8GyAehNbqjAthDphhH8FJmVq7J75eMJDXzuYLEJkQubB7Fa+8RHwDCXWOsSBhXxo4kUNByd6rlxL2KQ9jbpwFz2Hk26M4D6doUCd/RrCzEiHRXGLQ4aJzIM4h+t8El2HYo9D+Fe686+Jkzn3YBnIQBtStdguPIV/QPT3jLkOyQh5wgnHbEKsaMjDUw7Sp7iMoe512k1i64qPVM9aRQanyfOtEGfMTf/u6GvScSSdi6f6FR0DodJmvlEQUSH0=
  on:
    repo: everythingisdata/restapis-django-basics
    all_branches: true
