language: python
cache: pip
notifications:
  email: "${HEROKU_EMAIL}"
python:
- '3.6'
services:
- docker
before_script:
- pip install docker-compose
script:
- docker-compose run --rm app sh -c "python manage.py makemigrations"
- docker-compose run --rm  app sh -c "python manage.py migrate"
- docker-compose run --rm  app sh -c "python manage.py test  && flake8  --ignore E501,F811"
deploy:
  provider: heroku
  app: restapis-django-basics
  api_key:
    secure: PYfMMb9RjHB5A+uPdek2Ud8jdVLGXc1ywgPpQrr7azwqzEP0nD7eGtzPRAk5rm3U2IJEa6VixWj5eRrUoqYoNcT8RdQ+Tggd9gN3mT/u/a5C/Z2P57w89QShohZzaTDc1UbblFJxNiaBS843pmwatQiGDa9TLLZGw3WbrYDRsOiEMqbb/jPm9frfjbW/rteFX6f+1SN8F/G51dJCmNNUr9sNZfNEOlBeIWK04Z8zTGEP2gCBe2prMQEB/OKqjxwhf8IBs0fV4sm1oNcwmYvEBFxwQVKbjd01RRjppTQJvVKZ7ddfLvq5I8jTPIDCA+xDCsTdTvzyGJNRjeopmpUu/GjTzNMKJ2+eikKiD2pv+8Ji0FNatA8LTfyPjOoTk/SCit2cVUaLzIdiQQReQCp4EoMH79LSXQYgxIEVlkzUa6/IUZhkEdTK+Z6V3C3eTV7JxhDmiOjBo4VqhC5ZiUJQa+V4L5Acgs98uy4HMlF8V8euurwuKH+btOeVJqWgl5/9oTHTGc0qqVux4rIrwsBXOy0oypCdp4LPzXlf3QpFZAyT2inw/OOkMgs9+Ne/V7tf5uJXUe8njXFPNhGEiTIncGuY5UqtoHl6/5xUAoxIbwvSNbTTBN/d1WVDFMhAsY6UG4TJBOHuGMC/VFcX1cGLmQM8aTP+XXhlzTcHB44Ct1I=
  on:
    repo: everythingisdata/restapis-django-basics
    all_branches: true
