language: python
cache: pip
notifications:
  email: "${HEROKU_EMAIL}"
python:
- '3.6'
services:
- docker
before_script:
- pip install docker-compose
script:
- docker-compose run --rm app sh -c "python manage.py makemigrations"
- docker-compose run --rm  app sh -c "python manage.py migrate"
- docker-compose run --rm  app sh -c "python manage.py test  && flake8  --ignore E501,F811"
deploy:
  provider: heroku
  app: restapis-django-basics
  api_key:
    secure: FH96ERJrMKG1I1nDsxaFtEyy6yyQSHNE0jVSN/+vnZydltXRdNKrvJ5sD5TSO9wobbmRTa+QpwHuzbEuoEFLxrk5eoqvc9y5j4E80abHL3fXZvZJ/m+dxqV+m32pKlx2u60/lPYYzukqKZmqWZtXLbaJmghryzJZ4s0K6HLAG9L20d+QicYnGWApQbIqZ/hBQnf80L8q3XS747UhpWQDP3BuYZhxv3IXpPtOgUqmNZPT4WJ9pnSTqEo+aq3SScvoUa/q53iBQksNWD4VcTb0oIE2rwVzTapvHbrjP1I347KsbcRDmytOeu3LzAHgrIaopvM8e395jP0Osk3swPJE/qnTJ+QjiehiflJvyklIlMOm/t834Ql+OK/gIJwSpm2X6hM3JH58f6+4x/eV0QWtdZdN+Pxx7AJSpKX5vMAYxNq+MEp/AZTzfg0bjamK6BPffdcHqqiK4IlJUu7t1y/GnP0rrxddjKX9kolxZmxbit6eYVeg/OMtFUk51/r23SXmBHGm76LDRGaT1CN8noCznk4ILSN0HIu6kZ0wT32ebmhC5J7A6lkeRKnYqk6HAS49ISsCfcDD+xNnEcpq+W8R4+8qDvITKLV5Ta64FEH8JHE/PAEIlRoPZov/1jDhMSg388vEeXB1LGEmY+4MvjhB9EAJXCi7mxAL9+UIdgPDQ5c=
  on:
    repo: everythingisdata/restapis-django-basics
    all_branches: true
