language: python
cache: pip
notifications:
  email: "${HEROKU_EMAIL}"
python:
- '3.6'
services:
- docker
before_script:
- pip install docker-compose
script:
- docker-compose run --rm app sh -c "python manage.py makemigrations"
- docker-compose run --rm  app sh -c "python manage.py migrate"
- docker-compose run --rm  app sh -c "python manage.py test  && flake8  --ignore E501,F811"
deploy:
  provider: heroku
  app: restapis-django-basics
  api_key:
    secure: a/R7gcneOstv6y0Ly9Bk5MstLBCRpWKbWkNt2NVbMBnZhzAw6o2VEd2Wk6I8kd+0k/604iNTCntiSAxIBCcrCHjPdn47PU5uV0dDnp66MLZWBEcYCjHTMlqQEGuK7zOGjnkBbG3Jq2dD2MPlgozeSlKokwWG+oUqGGyGLiB/HQMGhZSmno0D4leSOzRgk9kbEhxcbwCZNUQgJ9fk0AAw9S3cCzdae7IBvVsvgIYE+aKVhmVxYfp2GeCFxklG+m05GqglsK4Hz3yOFlGKy4MdLy+l2ou8mLh9HzXIrcQvyWL1hUdEGUDuDrGfVVlcYu9ctdc9zndBXwhjJ5PkcxGWI+MGfRf+6L7QSvZQYJfJ3hDi5LRMD5cI6mXVZn5yXF4HPEO38k57iOHh3agxOWeXUL3aXMGR3EbDCGMmAayVU6pffB2Ubq6ixhX7Tc7+wpNbdZFtWnexTNnyM25nd1y5wMXLngLylv9NHRdeHCwLLb60RcktGE665qLyLEt+AywMlLTlmA/j+HSqt1Nrr4z+2G7ztA3hkudK7Qo6lsZoHP5EH6BS1ytfBsKy+ubvAZ/gDMC0ABZRPnhduUc39MSRQHWxRmDgNvIU48IGSkB3R1kuNVk53ogt86ZeVcX3vCTGxZuQBGOdhWIP7COk1yCmtsbBiR/vcFWl3bVQNxlu99U=
  on:
    repo: everythingisdata/restapis-django-basics
    all_branches: true
