language: python
cache: pip
notifications:
  email: "${HEROKU_EMAIL}"
python:
- '3.6'
services:
- docker
before_script:
- pip install docker-compose
script:
- docker-compose run --rm app sh -c "python manage.py makemigrations"
- docker-compose run --rm  app sh -c "python manage.py migrate"
- docker-compose run --rm  app sh -c "python manage.py test  && flake8  --ignore E501,F811"
deploy:
  provider: heroku
  app: restapis-django-basics
  api_key:
    secure: QYfyfStBOGVksVy1QvnehHnc8buToQMZEDnZVCugvBhttqYbF1JaKaVIefnKE4qiQvNRCwV063Aw477ZWI5b9vchBRT4IpZPi06Y+YpFU9EY1pL67uGHU/1z7qjvphdtTbOfj/rOuwDtvqkcryDHd6/g1RUrYg2L6c8b2IjI6ns5v4JIAlvmz42vnB1YqDuBsgohJH/nEETAYvfxWaYsCMaXDTOk6L6J5MB66I6OA8mQtuBWowZMSetrQqr0a8ip5BjXO+g0ZL+XvdEZrAARpcviqV2+LyMngMOEmuKcEAYdlgRB+JyWGffWVoAzK0/1oCbgdxAO4O7eICwtxCYf/APB/YCjHyl8DqK3LKvPXq9979NgGlMY8epPJ40oTYXqH5YnO/qmTGssCU76cQei/gltl0oTIeK7NeVZxfmNGSEwfGblCsogNcFBDEZ0t/mfQphXltvRsxoz+jC9Pl6yXJTgxkD5uj5N8Ysfelo9sfDia/QWMIDgGnaFYZx9yrLJLcC9DXXVn6VaRCao0i6bGYNM6Uz7GC67XZtKXTiKZL8Gg5gfbmfUsqr8DuN5/rERi9DhIv6DNcp1r8PZGIw+a14QqtRyRydXxz3PpUJJ2eRCC2rGHLTwi56VcF+BkoEhCaU/bpWWCPQ4UQZKL4inehMJMOIaW490RsSc1wiRh3I=
  on:
    repo: everythingisdata/restapis-django-basics
    all_branches: true
