version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ".:/app"
    command: >
      sh -c  "sleep:10;
      python manage.py  makemigrations --noinput  &&
      python manage.py  migrate  &&
      python manage.py  runserver 0.0.0.0:8000        "
